import uuid
from datetime import datetime
from typing import Protocol

from app.domain.entities.ai_job import AIJob


class AIJobRepository(Protocol):
    async def save(self, job: AIJob) -> None: ...
    async def get_by_id(self, job_id: uuid.UUID) -> AIJob | None: ...
    async def get_by_queue_id(self, queue_id: str) -> AIJob | None: ...
    async def get_by_idempotency_key(self, key: str) -> AIJob | None: ...
    async def update_status(self, job_id: uuid.UUID, status: str) -> None: ...
    async def update_result(
        self, job_id: uuid.UUID, result: str | None, status: str, finish_dt: datetime, duration_ms: int
    ) -> None: ...
    async def increment_retry(self, job_id: uuid.UUID) -> None: ...
