from prometheus_client import Counter, Gauge, Histogram

total_messages_consumed = Counter("total_messages_consumed", "Total messages consumed")
total_documents_processed = Counter("total_documents_processed", "Total documents processed")
total_success = Counter("total_success", "Total AI_RETURN_CD=SUCCESS")
total_ng = Counter("total_ng", "Total status NG")
total_document_error = Counter("total_document_error", "Total DOCUMENT_ERROR")
total_internal_error = Counter("total_internal_error", "Total INTERNAL_ERROR")
total_dlq = Counter("total_dlq", "Total DLQ")
avg_processing_time_ms = Gauge("avg_processing_time_ms", "Average processing time ms")
p95_processing_time_ms = Histogram("p95_processing_time_ms", "P95 processing time", buckets=[1000, 3000, 5000, 10000, 20000, 30000])
ocr_failure_count = Counter("ocr_failure_count", "OCR failure count")
yolo_failure_count = Counter("yolo_failure_count", "YOLO failure count")
barcode_decode_failure_count = Counter("barcode_decode_failure_count", "Barcode decode failure")
gpu_memory_usage = Gauge("gpu_memory_usage", "GPU memory usage MB")
worker_active_jobs = Gauge("worker_active_jobs", "Active jobs")
rabbitmq_queue_depth = Gauge("rabbitmq_queue_depth", "Queue depth")
retry_count = Counter("retry_count", "Retry count")
duplicate_message_count = Counter("duplicate_message_count", "Duplicate messages")
