from typing import Final

INV: Final[str] = "INV"
DN: Final[str] = "DN"
BILLING: Final[str] = "BILLING"
RECEIPT: Final[str] = "RECEIPT"
TAX: Final[str] = "TAX"
SUPPORTING: Final[str] = "SUPPORTING"
OTHER: Final[str] = "OTHER"

ALL_TYPES: Final[frozenset[str]] = frozenset({INV, DN, BILLING, RECEIPT, TAX, SUPPORTING, OTHER})
INVOICE: Final[str] = "INVOICE"
DELIVERY_NOTE: Final[str] = "DELIVERY_NOTE"
BILLING_DOCUMENT: Final[str] = "BILLING_DOCUMENT"
RECEIPT_DOCUMENT: Final[str] = "RECEIPT_DOCUMENT"
TAX_DOCUMENT: Final[str] = "TAX_DOCUMENT"
SUPPORTING_DOCUMENT: Final[str] = "SUPPORTING_DOCUMENT"
OTHER_DOCUMENT: Final[str] = "OTHER_DOCUMENT"

DOC_TYPE_MAP: Final[dict[str, str]] = {
    INV: INVOICE,
    DN: DELIVERY_NOTE,
    BILLING: BILLING_DOCUMENT,
    RECEIPT: RECEIPT_DOCUMENT,
    TAX: TAX_DOCUMENT,
    SUPPORTING: SUPPORTING_DOCUMENT,
    OTHER: OTHER_DOCUMENT,
}

MAIN_DOCUMENT: Final[str] = "MAIN_DOCUMENT"
SECOND_DOCUMENT: Final[str] = "SECOND_DOCUMENT"
SUPPORTING_CATEGORY: Final[str] = "SUPPORTING_DOCUMENT"

ALL_CATEGORIES: Final[frozenset[str]] = frozenset({MAIN_DOCUMENT, SECOND_DOCUMENT, SUPPORTING_CATEGORY})
