from typing import Final

SUCCESS: Final[str] = "SUCCESS"
DOCUMENT_ERROR: Final[str] = "DOCUMENT_ERROR"
INTERNAL_ERROR: Final[str] = "INTERNAL_ERROR"
DLQ_ERROR: Final[str] = "DLQ_ERROR"
VALIDATION_ERROR: Final[str] = "VALIDATION_ERROR"
TIMEOUT_ERROR: Final[str] = "TIMEOUT_ERROR"
PARTIAL_SUCCESS: Final[str] = "PARTIAL_SUCCESS"

RETRYABLE_CODES: Final[frozenset[str]] = frozenset({INTERNAL_ERROR, TIMEOUT_ERROR})
NON_RETRYABLE_CODES: Final[frozenset[str]] = frozenset({SUCCESS, DOCUMENT_ERROR, DLQ_ERROR, VALIDATION_ERROR})
