from typing import Final

OK: Final[str] = "OK"
NG: Final[str] = "NG"

RECEIVED: Final[str] = "RECEIVED"
VALIDATING_PAYLOAD: Final[str] = "VALIDATING_PAYLOAD"
DOWNLOADING_DOCUMENT: Final[str] = "DOWNLOADING_DOCUMENT"
VALIDATING_DOCUMENT: Final[str] = "VALIDATING_DOCUMENT"
CONVERTING_DOCUMENT: Final[str] = "CONVERTING_DOCUMENT"
RUNNING_OCR: Final[str] = "RUNNING_OCR"
RUNNING_DETECTION: Final[str] = "RUNNING_DETECTION"
RUNNING_BARCODE: Final[str] = "RUNNING_BARCODE"
RUNNING_BUSINESS_VALIDATION: Final[str] = "RUNNING_BUSINESS_VALIDATION"
BUILDING_RESULT: Final[str] = "BUILDING_RESULT"
PUBLISHED: Final[str] = "PUBLISHED"
FAILED_DOCUMENT_ERROR: Final[str] = "FAILED_DOCUMENT_ERROR"
FAILED_INTERNAL_ERROR: Final[str] = "FAILED_INTERNAL_ERROR"
DLQ: Final[str] = "DLQ"

COMPLETED: Final[str] = "Completed"
PROCESSING: Final[str] = "Processing"
FAILED: Final[str] = "Failed"
PENDING: Final[str] = "Pending"
