# Only constants actively used by the codebase. Add more when features need them.
OK: str = "OK"
NG: str = "NG"
COMPLETED: str = "COMPLETED"
FAILED: str = "FAILED"
DLQ: str = "DLQ"
SUCCESS: str = "SUCCESS"
DOCUMENT_ERROR: str = "DOCUMENT_ERROR"
INTERNAL_ERROR: str = "INTERNAL_ERROR"
PROCESSING: str = "PROCESSING"
